- R/indicator_1-2-1.R
- automation_helper_functions.R
- data/indicator_1-2-1.csv
- meta/1-2-1.yml
- meta/fr/1-2-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/254#issue-2271340944
> GRIP 1.2.1: Added data for territories and updated data sources

- indicator-config/11-b-1.yml
- indicator-config/13-1-2.yml
- indicator-config/fr/1-5-3.yml
- indicator-config/fr/11-b-1.yml
- indicator-config/fr/13-1-2.yml
- meta/11-b-1.yml
- meta/13-1-2.yml
- meta/fr/1-5-3.yml
- meta/fr/11-b-1.yml
- meta/fr/13-1-2.yml
- translations/en/proxy.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/287
> Issue 287: Updated indicator 1.5.3, 11.b.1, and 13.1.2

- indicator-config/1-5-4.yml
- indicator-config/11-b-2.yml
- indicator-config/13-1-3.yml
- indicator-config/fr/1-5-4.yml
- indicator-config/fr/11-b-2.yml
- indicator-config/fr/13-1-2.yml
- indicator-config/fr/13-1-3.yml
- meta/1-5-4.yml
- meta/11-b-2.yml
- meta/13-1-3.yml
- meta/fr/1-5-4.yml
- meta/fr/11-b-2.yml
- meta/fr/13-1-3.yml
- translations/en/proxy.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/288
> Issue 288: Updated indicator 1.5.4, 11.b.2, and 13.1.3 to be proxy indicators and updated page content

- data/indicator_1-4-1.csv
- indicator-config/1-4-1.yml
- indicator-config/1-5-4.yml
- indicator-config/11-b-2.yml
- indicator-config/13-1-3.yml
- indicator-config/fr/1-4-1.yml
- indicator-config/fr/1-5-4.yml
- indicator-config/fr/11-b-2.yml
- indicator-config/fr/13-1-3.yml
- meta/1-4-1.yml
- meta/1-a-2.yml
- meta/fr/1-4-1.yml
- meta/fr/1-5-2.yml
- metadata_schema.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/55#issuecomment-2358629175
Fixed typos and missing translations for indicator 1.5.2, 1.5.4, 11.b.2, 13.1.3, and 1.a.2.
Increased maximum number of sources to be displayed to 10.
> GRIP 1.4.1: Added new series, updated data and metadata

- data/indicator_1-3-1.csv
- indicator-config/1-3-1.yml
- indicator-config/1-4-1.yml
- indicator-config/fr/1-4-1.yml
- indicator-config/fr/1-5-4.yml
- indicator-config/fr/11-b-2.yml
- indicator-config/fr/13-1-3.yml
- meta/1-3-1.yml
- meta/fr/1-3-1.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/5
> GRIP 1.3.1: Updated Indicator with new data and new series

- indicator-config/fr/2-c-1.yml
- meta/2-c-1.yml
- meta/fr/2-c-1.yml
- #273 
- updated source link to
- EN: https://de-public-statsuite.fao.org/vis?pg=0&bp=true&snb=3&vw=tb&df[ds]=ds-release&df[id]=DF_AG_FPA_CFPI_2C1&df[ag]=FAO&df[vs]=1.0&dq=A...124........&pd=2015%2C&to[TIME_PERIOD]=false
- FR: https://de-public-statsuite.fao.org/vis?pg=0&bp=true&snb=3&vw=tb&df[ds]=ds-release&df[id]=DF_AG_FPA_CFPI_2C1&df[ag]=FAO&df[vs]=1.0&dq=A...124........&pd=2015%2C&to[TIME_PERIOD]=false&ly[cl]=TIME_PERIOD&lc=fr
- add data reporting on FR page
- add FR metadata definition from https://worldbank.github.io/sdg-metadata/metadata/fr/all/#2-c-1
> GIF transfer - 2.c.1 Add FR metadata

- meta/2-b-1.yml
- meta/fr/2-b-1.yml
- translations/en/data.yml
- translations/fr/data.yml
> GRIP 2.b.1

- meta/fr/2-b-1.yml
> GRIP 2.b.1 part 2 attempt 2

- indicator-config/2-a-1.yml
- meta/fr/2-a-1.yml
- translations/en/chart.yml
- translations/fr/chart.yml
- translations/fr/data.yml
- #276 
- set graph titles directly in indicator_config file
- add FR sources
> GRIP 2.a.1 part 2

- meta/fr/2-c-1.yml
- #273 
- add (en anglais seulement) to FR source
> GRIP 2.c.1 part 2

- R/indicator_2-a-2.R
- data/indicator_2-a-2.csv
- indicator-config/2-a-2.yml
- meta/2-a-2.yml
- meta/fr/2-a-2.yml
- translations/en/data.yml
- translations/fr/data.yml
- #258 
- New automated script for indicator 2.a.2 fetches data using the OECD API
- Added disaggregations for ODA and OOF disbursements
- Updated metadata
- Updated source links to EN/FR versions of the CRS table on the new OECD Data Explorer
- Added data translations
> GRIP 2.a.2

- translations/en/data.yml
- translations/fr/data.yml
> GRIP 2.a.2 add missing data translation

- meta/fr/2-5-2.yml
- translations/en/meta.yml
- translations/fr/meta.yml
- #326 
- minor FR metadata updates and corrections
- add translation for "United Nations Sustainable Development Goals Metadata"
> GRIP 2.5.2

- indicator-config/fr/2-4-1.yml
- meta/2-4-1.yml
- meta/fr/2-4-1.yml
- translations/fr/custom.yml
> GRIP 2.4.1

- indicator-config/fr/2-5-1.yml
- meta/fr/2-5-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/325
> GRIP 2.5.1: Added method of computation and graph titles

- indicator-config/2-2-3.yml
- meta/fr/2-2-3.yml
- #6
- set data_start_values
- force comments and limitations FR to show even if empty
> GRIP 2.2.3 part 2

- indicator-config/2-4-1.yml
- indicator-config/fr/2-4-1.yml
- meta/2-4-1.yml
- meta/fr/2-4-1.yml
- #324 
- add proxy tag for Farm output value per hectare series
- fix formatting of numbered list in metadata en/fr
> GRIP 2.4.1 part 2

- meta/14-5-1.yml
- meta/fr/14-5-1.yml
> GRIP 14.5.1

- translations/fr/chart.yml
> GRIP 14.4.1 part 2

- data/indicator_14-4-1.csv
> GRIP 14.4.1 part 3

- indicator-config/1-2-2.yml
- indicator-config/fr/1-2-2.yml
- meta/1-2-2.yml
- meta/fr/1-2-2.yml
> GRIP 1.2.2

- indicator-config/1-a-1.yml
- meta/1-a-1.yml
- meta/fr/1-a-1.yml
- #58
- Metadata formatting fixes
- Limit number of decimals showing in graph/table
> GRIP 1.a.1 part 2

- meta/2-c-1.yml
- meta/fr/2-c-1.yml
- translations/en/data.yml
- translations/fr/data.yml
- #276 
- Fix graph title appearing in English on FR page 2.a.1
- #273
- Add method of computation EN/FR 2.c.1
> Goal 2 review

- meta/1-a-1.yml
- meta/fr/1-a-1.yml
> GRIP 1.a.1 part 3

- indicator-config/1-2-2.yml
- indicator-config/fr/1-2-2.yml
- meta/1-2-2.yml
- meta/fr/1-2-2.yml
> GRIP 1.2.2 attempt 2

- meta/1-a-1.yml
- meta/fr/1-a-1.yml
> GRIP 1.a.1 part 4

- meta/1-a-1.yml
- meta/fr/1-a-1.yml
- #58 
- Reformat definition using \<p> tags, should force \<ul> block to display correctly.
> GRIP 1.a.1 part 5

- indicator-config/1-2-2.yml
- indicator-config/fr/1-2-2.yml
- meta/1-2-2.yml
- meta/fr/1-2-2.yml
- #405 
- Restore previous metadata entries EN/FR
- Add source EN/FR
- Expand page content EN/FR
- Set geographic region to Canada
> GRIP 1.2.2 part 3

- meta/1-5-3.yml
- meta/11-b-1.yml
- meta/13-1-2.yml
- meta/fr/1-5-3.yml
- meta/fr/11-b-1.yml
- meta/fr/13-1-2.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/287#issuecomment-2393790185
> GRIP 1.5.3 / 11.b.1 / 13.1.2: Added statement on proxy

- indicator-config/1-2-1.yml
- indicator-config/fr/1-1-1.yml
- indicator-config/fr/1-2-1.yml
- meta/fr/1-2-1.yml
- #320 
- Minor typo correction in banner
- #254 
- Update FR graph title
- Link to FR page for QoL framework
- Minor typo correction in metadata definition
> GRIP 1.1.1 and 1.2.1 review

- meta/1-5-4.yml
- meta/11-b-2.yml
- meta/13-1-3.yml
- meta/fr/1-5-4.yml
- meta/fr/11-b-2.yml
- meta/fr/13-1-3.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/288#issuecomment-2391428728
> GRIP 1.5.4 / 11.b.2 / 13.1.3: Updated sources, comments and limitations, and definition

- meta/1-3-1.yml
- meta/fr/1-3-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/5#issuecomment-2393998840
> GRIP 1.3.1 review

- indicator-config/fr/12-a-1.yml
- meta/fr/12-a-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/331#issue-2470821402
> GRIP 12.a.1

- data/indicator_1-4-1.csv
- indicator-config/1-4-1.yml
- indicator-config/fr/1-4-1.yml
- meta/1-4-1.yml
- meta/fr/1-4-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/55#issuecomment-2389538066
> GRIP 1.4.1: Updated graph titles, removed dropdown menu for some series, updated data start values, and added comments and limitation

- meta/fr/1-5-4.yml
- meta/fr/11-b-2.yml
- meta/fr/13-1-3.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/288#issuecomment-2394328799
> GRIP 1.5.4 / 11.b.2 / 13.1.3: Updated source in FR page

- meta/fr/1-b-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/423#issue-2567058962
> GRIP 1.b.1: Updated definition and concepts in the FR page

- meta/1-a-2.yml
- meta/fr/1-a-2.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/323#issuecomment-2394332161
> GRIP 1.a.2: Updated sources to match ENG page

- translations/fr/global_indicators.yml
- #331 
- Fix FR translation for 12.a.1 indicator name
> GRIP 12.a.1 part 2

- indicator-config/fr/12-b-1.yml
- meta/12-b-1.yml
- meta/fr/12-b-1.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/332#issue-2470835636
> GRIP 12.b.1

- meta/fr/12-b-1.yml
> GRIP 12.b.1 part 2

- data/indicator_1-4-1.csv
- meta/1-4-1.yml
- meta/fr/1-4-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/55#issuecomment-2396820951
> GRIP 1.4.1: Updated CSV file and sources

- data/indicator_1-4-1.csv
> GRIP 1.4.1: reorder data columns

- meta/14-4-1.yml
- meta/14-5-1.yml
- https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/327#issuecomment-2397056875
- https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/328#issuecomment-2397060622
> Goal 14 review

- data/indicator_1-4-1.csv
> remove duplicate data and add precision

- meta/fr/12-3-1.yml
- meta/fr/12-a-1.yml
- https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/331#issuecomment-2400669470
> GRIP 12.a.1 review

- meta/12-a-1.yml
- https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/331#issuecomment-2402246034
- remove '(see concepts below)' from definition
> 12.a.1 review

- indicator-config/12-4-1.yml
- indicator-config/fr/12-4-1.yml
- meta/12-4-1.yml
- meta/fr/12-4-1.yml
- translations/en/proxy.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/285
> GRIP 12.4.1: Updated sources and added new content to non statistical indicator page

- meta/12-2-2.yml
- meta/8-4-2.yml
- meta/fr/12-2-2.yml
- meta/fr/8-4-2.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/329
> GRIP 8.4.2 and 12.2.2: Updated FR method of computation, comments and limitations, and translations

- R/indicator_4-1-2.R
- data/indicator_4-1-2.csv
- indicator-config/4-1-2.yml
- indicator-config/fr/4-1-2.yml
- meta/fr/4-1-2.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/195
> GRIP 4.1.2: Updated metadata and headline series

- data/indicator_4-1-1.csv
- indicator-config/4-1-1.yml
- indicator-config/fr/4-1-1.yml
- meta/4-1-1.yml
- meta/fr/4-1-1.yml
- translations/en/proxy.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/336
> GRIP 4.1.1: Updated metadata and added proxy label

- indicator-config/4-3-1.yml
- meta/4-3-1.yml
- meta/fr/4-3-1.yml
- translations/en/chart.yml
- translations/en/proxy.yml
- translations/fr/chart.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/338
> GRIP 4.3.1: Added proxy label and updated metadata

- meta/4-c-1.yml
- meta/fr/4-c-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/341
> GRIP 4.c.1: Updated FR page with new definition

- meta/fr/6-1-1.yml
- meta/fr/6-5-2.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/353
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/355
> GRIP 6.1.1 and 6.5.1: Updated FR method of computation, definition, and source

- indicator-config/6-3-2.yml
- meta/6-3-2.yml
- meta/fr/6-3-2.yml
- translations/en/data.yml
- translations/en/proxy.yml
- translations/fr/data.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/354
> GRIP 6.3.2: Updated FR metadata

- meta/7-1-1.yml
- meta/7-1-2.yml
- meta/7-3-1.yml
- meta/fr/7-1-1.yml
- meta/fr/7-1-2.yml
- meta/fr/7-3-1.yml
> Goal 7 revisions

- R/indicator_8-6-1.R
- data/indicator_8-6-1.csv
- indicator-config/8-a-1.yml
- #367 
- remove headline duplicated by data start values
- #374 
- display both commitments and disbursements with data start values
> Goal 8 part 2

- indicator-config/6-3-1.yml
- meta/6-3-1.yml
- translations/en/data.yml
- translations/fr/data.yml
- #264 
- improve some data translations
- minor formatting fix in EN method of computation
> 6.3.1 part 2

- R/wip/indicator_6-4-1.R
- R/wip/indicator_6-4-2.R
- data/indicator_6-4-1.csv
- data/indicator_6-4-2.csv
- indicator-config/6-4-1.yml
- indicator-config/6-4-2.yml
- meta/6-4-1.yml
- meta/6-4-2.yml
- meta/fr/6-4-1.yml
- meta/fr/6-4-2.yml
- translations/en/data.yml
- translations/fr/data.yml
> GIF 6.4.1 and 6.4.2

- R/wip/indicator_6-4-1.R
- data/indicator_6-4-1.csv
- indicator-config/6-4-1.yml
- #265 
- set Overall disaggregation as headline
> 6.4.1 - Set headline

- indicator-config/5-1-1.yml
- indicator-config/fr/5-1-1.yml
- meta/5-1-1.yml
- meta/5-2-1.yml
- meta/fr/5-1-1.yml
- meta/fr/5-2-1.yml
- translations/en/proxy.yml
- translations/fr/chart.yml
- translations/fr/data.yml
- translations/fr/proxy.yml
> 5.1.1 and 5.2.1

- translations/en/chart.yml
- #344
- update EN chart title to reflect proxy data and be consistent with FR graph title
> 5.2.2 - chart title

- indicator-config/6-6-1.yml
- meta/6-6-1.yml
- meta/6-a-1.yml
- meta/fr/6-3-1.yml
- meta/fr/6-6-1.yml
- meta/fr/6-a-1.yml
- #264 
- fix superscript for cubic metres
- #356
- add proxy explanation in comments
- #199 
- unpublish data/definitions and set to exploring data sources
> Goal 6 revisions

- R/indicator_5-4-1.R
- data/indicator_5-4-1.csv
- indicator-config/5-3-1.yml
- indicator-config/5-4-1.yml
- meta/5-3-1.yml
- meta/5-4-1.yml
- meta/fr/5-3-1.yml
- meta/fr/5-4-1.yml
- translations/en/data.yml
- translations/fr/chart.yml
- translations/fr/data.yml
- translations/fr/proxy.yml
- #345 
- #347 
- added 2022 data and corresponding updates to metadata EN/FR
> 5.3.1 and 5.4.1

- indicator-config/5-4-1.yml
- meta/5-4-1.yml
- meta/fr/5-4-1.yml
- #347 
- update UN tier and custodian agencies to match 2024 UN metadata
- fix data start values
> 5.4.1 part 2

- indicator-config/fr/5-1-1.yml
- indicator-config/fr/5-a-2.yml
- #350 #342
- Add missing proxy tag for 5.a.2 FR
- Add non-breaking spaces where needed in FR page content (5.1.1, 5.a.2)
> Goal 5 final touches

- translations/fr/data.yml
- #505 
- fix typo in "Territoires du Nord" spelling
> Goal 9 final touches

- indicator-config/fr/5-c-1.yml
- meta/5-5-1.yml
- meta/5-6-2.yml
- meta/fr/5-5-1.yml
- meta/fr/5-6-2.yml
- #348 
- Remove comment EN/FR
- #550 
- Add FR definition
- #352
- FR page content change to match EN page content
> Goal 5 revisions

- data/indicator_9-c-1.csv
- meta/9-1-2.yml
- meta/9-2-1.yml
- meta/9-3-2.yml
- meta/9-4-1.yml
- meta/9-5-2.yml
- meta/fr/9-1-2.yml
- meta/fr/9-2-1.yml
- meta/fr/9-3-2.yml
- meta/fr/9-4-1.yml
- meta/fr/9-5-2.yml
- #496 
- improve definition and add proxy explanation EN/FR
- #506
- remove zeros representing NA values before 5G coverage was made available in Canada
- #503, #501, #500, #497
- add proxy blurb
> Goal 9 revisions

- meta/fr/3-1-1.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/376#issue-2531455983
> GIF 3.1.1: Updated Typo and Unit Translations

- meta/11-1-1.yml
- meta/11-3-1.yml
- meta/11-6-1.yml
- meta/fr/11-1-1.yml
- meta/fr/11-3-1.yml
- meta/fr/11-4-1.yml
- meta/fr/11-6-1.yml
- translations/fr/proxy.yml
- #516
- Remove unnecessary quotation marks
- #360
- Add functional hyperlinks
- #518 
- typo FR
- #519
- switch from generic data-comp to data-comp-national
- typos FR
> Goal 11 final touches + reviews 11.1.1, 11.3.1 

- R/indicator_3-2-2.R
- data/indicator_3-2-2.csv
- indicator-config/3-2-1.yml
- indicator-config/3-2-2.yml
- meta/3-2-2.yml
- meta/fr/3-2-2.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/228#issuecomment-2397646317
> GIF 3.2.2: Updated Data and Metadata fields

- R/indicator_3-2-2.R
- data/indicator_3-2-2.csv
- indicator-config/3-2-2.yml
- meta/3-3-1.yml
- meta/fr/3-3-1.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/450#issue-2578855496
> GIF 3.3.1: Updated unit of measure, method of computation and typo

- R/indicator_3-4-1.R
- data/indicator_3-4-1.csv
- indicator-config/3-3-5.yml
- indicator-config/3-4-1.yml
- meta/3-4-1.yml
- meta/fr/3-4-1.yml
- translations/en/data.yml
- translations/en/proxy.yml
- translations/fr/data.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/469
> GIF 3.4.1: Updated R script and changed indicator to proxy

- indicator-config/3-5-2.yml
- meta/3-5-2.yml
- meta/fr/3-5-2.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/471#issue-2589850802
> GIF 3.5.2: Updated Definitions and added comments and limitations

- R/indicator_3-7-2.R
- data/indicator_3-7-2.csv
- indicator-config/3-7-1.yml
- meta/3-7-2.yml
- meta/fr/3-7-1.yml
- meta/fr/3-7-2.yml
- translations/en/data.yml
- translations/fr/chart.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/474
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/475
> GIF 3.7.1 and 3.7.2: Updated R script, method of computation, and comments and limitations

- meta/11-4-1.yml
- meta/fr/11-1-1.yml
- meta/fr/11-4-1.yml
- translations/en/proxy.yml
- translations/fr/proxy.yml
- #516
- typo
- #518
- Edit proxy title
> Goal 11 revisions

- indicator-config/3-8-2.yml
- meta/fr/3-6-1.yml
- meta/fr/3-8-2.yml
- translations/en/data.yml
- translations/fr/data.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/477#issue-2619325375
> GIF 3.8.2: Updated proxy titles and added definitions and comments and limitations

- indicator-config/fr/3-9-1.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/478
> GIF 3.9.1 and 3.8.2: Updated Indicator page to have "Data not available" for 3.9.1 and updated proxy title for 3.8.2

- indicator-config/1-5-4.yml
- indicator-config/11-b-2.yml
- indicator-config/13-1-3.yml
- indicator-config/fr/1-5-4.yml
- indicator-config/fr/11-b-2.yml
- indicator-config/fr/13-1-3.yml
- meta/1-5-4.yml
- meta/11-b-2.yml
- meta/13-1-3.yml
- meta/fr/1-5-4.yml
- meta/fr/11-b-2.yml
- meta/fr/13-1-3.yml
- 1.5.4/11.b.2/13.1.3
- Fix Sendai Framework link in page content that was linking to BC's emergency management legislation page. 
- Add link to BC's emergency management legislation page in page content.
- Update wording of source text for BC's emergency management legislation to match source page title.
> Goal 11 revision part 2

- indicator-config/3-9-2.yml
- meta/3-9-3.yml
- meta/fr/3-9-3.yml
- translations/fr/chart.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/481#issue-2619394648
> GIF 3.9.3: Updated definition, calculations, and source information

- data/indicator_3-a-1.csv
- indicator-config/3-8-2.yml
- meta/3-a-1.yml
- meta/fr/3-a-1.yml
- translations/en/data.yml
- translations/fr/data.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/482#issue-2619420893
> GIF 3.a.1: Updated with new data and updated comments and limitations

- R/indicator_3-b-1.R
- data/indicator_3-b-1.csv
- indicator-config/3-8-2.yml
- indicator-config/3-b-1.yml
- meta/3-b-1.yml
- meta/fr/3-b-1.yml
- translations/en/chart.yml
- translations/en/data.yml
- translations/fr/chart.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/483#issue-2619444935
> GIF 3.b.1: Updated the indicator with data and information from CIF 3.9.1

- indicator-config/3-8-2.yml
- meta/3-8-2.yml
- translations/en/data.yml
- translations/fr/data.yml
- #477 
- Deleted extra indicator_available key in metadata file to attempt to fix the issue where the 3.8.2 proxy title is not being translated
> Attempt to fix 3.8.2 proxy title

- R/indicator_3-b-2.R
- R/indicator_3-c-1.R
- data/indicator_3-b-2.csv
- indicator-config/3-b-2.yml
- meta/3-b-2.yml
- meta/3-c-1.yml
- meta/fr/15-b-1.yml
- meta/fr/17-19-1.yml
- meta/fr/17-3-1.yml
- meta/fr/17-9-1.yml
- meta/fr/3-b-2.yml
- meta/fr/3-c-1.yml
- meta/fr/3-d-1.yml
- meta/fr/4-b-1.yml
- translations/en/data.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/484
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/487
> GIF 3.b.2 and 3.c.1

- data/indicator_15-1-2.csv
- data/indicator_3-c-1.csv
- indicator-config/15-1-2.yml
- meta/fr/15-1-2.yml
- translations/en/chart.yml
- translations/en/data.yml
- translations/fr/chart.yml
- translations/fr/data.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/537
> GIF Indicator 15.1.2: Updated definitions and graph titles

- meta/15-3-1.yml
- meta/fr/15-3-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/539
> GIF Indicator 15.3.1: Updated source and definitions

- indicator-config/15-6-1.yml
- indicator-config/fr/15-6-1.yml
- meta/15-6-1.yml
- meta/fr/15-6-1.yml
- translations/en/proxy.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/292
> GIF 15.6.1: Updated proxy title, source information, and link

- indicator-config/fr/15-8-1.yml
- meta/15-6-1.yml
- meta/15-7-1.yml
- meta/15-8-1.yml
- meta/15-c-1.yml
- meta/fr/15-6-1.yml
- meta/fr/15-7-1.yml
- meta/fr/15-8-1.yml
- meta/fr/15-9-1.yml
- meta/fr/15-c-1.yml
- translations/en/proxy.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/156
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/293
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/549
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/553
> GIF 15.7.1, 15.8.1, 15.9.1, 15.c.1: Updated definitons, source links, and indicator titles

- R/indicator_10-1-1.R
- data/indicator_10-1-1.csv
- data/indicator_10-c-1.csv
- indicator-config/10-1-1.yml
- indicator-config/16-1-3.yml
- meta/fr/13-2-2.yml
- translations/en/data.yml
- translations/fr/chart.yml
- translations/fr/data.yml
- #317
- Change graph type to bar
- #318 
- Add FR graph title
- #319 
- Add missing translation keys
- #526
- Align EN and FR definitions
- #37 
- Update script to automatically add new data
- Update with new data
- Add disaggregation for geography
- Split "Household income quintile or decile" into separate categories: "Household income quintile" and "Household income decile"
- #515
- Add missing translation keys
> Revisions 16.1.3, 16.1.4, 16.2.1, 13.2.2, 10.1.1, 10.c.1

- R/indicator_10-1-1.R
- data/indicator_10-1-1.csv
- translations/fr/data.yml
- #37 
- Add geographical disaggregation for income per capita series
- #515
- typo
> Revisions 10.1.1, 10.c.1 part 2

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- .github/workflows/test-pull-requests.yml
- .github/workflows/update-progress-measures.yml
- scripts/requirements.txt
- Update the progress measure workflow for python 3.10
- Move references to packaging library to scripts/requirements.txt
> More changes for python 3.10 update

- meta/16-3-3.yml
- #558 
- Add "This is a proxy indicator." before the existing comments and limitations.
> 16.3.3 part 2

- indicator-config/16-6-1.yml
- indicator-config/16-9-1.yml
- meta/fr/16-6-1.yml
- #563 
- Add back FR source organization (accidentally removed)
- #295 
- Set geographical coverage area for headline. Bug: Graph is not displaying.
> 16.6.1 and 16.9.1 part 2

- data/indicator_15-1-1.csv
- meta/fr/15-a-1.yml
- meta/fr/15-b-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/536
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/294
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/552
> Updated Indicator 15.1.1, 15.a.1, and 15.b.1

- data/indicator_17-2-1.csv
- indicator-config/17-2-1.yml
- meta/17-2-1.yml
- meta/fr/17-2-1.yml
- translations/en/data.yml
- translations/en/proxy.yml
- translations/fr/data.yml
- translations/fr/proxy.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/304#issuecomment-2578447121
> Updated 17.2.1 with new source links and updated French translations

- meta/16-10-2.yml
- meta/fr/16-10-2.yml
> 16.10.2 source org name

- data/indicator_17-6-1.csv
- indicator-config/17-5-1.yml
- indicator-config/17-9-1.yml
- indicator-config/fr/17-5-1.yml
- indicator-config/fr/17-9-1.yml
- meta/17-1-1.yml
- meta/17-16-1.yml
- meta/17-5-1.yml
- meta/17-9-1.yml
- meta/fr/17-1-1.yml
- meta/fr/17-5-1.yml
- meta/fr/17-9-1.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/300
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/298
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/306
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/588
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/297
> Updated indicators with P0 Priority status

- translations/en/frontpage.yml
- translations/en/general.yml
- translations/en/header.yml
- translations/en/status.yml
- translations/fr/frontpage.yml
- translations/fr/general.yml
- translations/fr/header.yml
- translations/fr/menu.yml
- translations/fr/status.yml
https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/issues/603#issue-2712913720
> Generic content update

- meta/fr/2-3-2.yml
- meta/fr/6-2-1.yml
- meta/fr/6-5-1.yml
- meta/fr/6-6-1.yml
- meta/fr/7-b-1.yml
- translations/fr/global_indicators.yml
- #308 
- Align 7.b.1 indicator title in FR with the EN indicator title
- Some spelling and wording fixes
> En recherche de sources de données - partie 2

- R/indicator_3-b-2.R
- data/indicator_3-b-2.csv
Switch order of disaggregation and value columns so that the value column is the last one (3.b.2)
> 3.b.2 column ordering

- meta/11-2-1.yml
- meta/fr/11-2-1.yml
- https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/issues/557
> add limitations note 11.2.1

- data/indicator_4-5-1.csv
- indicator-config/4-5-1.yml
- #754
- Fix typos in data and data_start_values
- Change graph type to from bar to line
> Fixes needed - Goal 4 part 2

- indicator-config/4-5-1.yml
- #754 
- Change graph type back to bar chart
- Add Primary education to data_start_values so that _Proportion of students achieving a minimum proficiency level in math/reading_ series show some data by default
> Fixes needed - Goal 4 part 3

- data/indicator_4-5-1.csv
- indicator-config/4-5-1.yml
- #754 
- re-organize parity indices as units
- remove language test parity and native parity indices because definitions are unknown
> Fixes needed - Goal 4 part 4

- indicator-config/11-5-3.yml
- meta/11-5-3.yml
- meta/fr/11-5-3.yml
- translations/en/global_indicators.yml
- translations/fr/global_indicators.yml
> new indicator 11.5.3

- meta/11-5-3.yml
- meta/fr/11-5-3.yml
- #666
- HTML link to UNDRR in metadata
> new indicator 11.5.3 part 2

- meta/fr/11-5-3.yml
- translations/fr/global_indicators.yml
- #666 
- Use official French title from UN for 11.5.3
> official fr indicator title

- meta/fr/11-5-1.yml
- meta/fr/11-5-2.yml
- meta/fr/11-5-3.yml
- #666 
- Copy target text for 11.5 from official UN source
> correct 11.5 fr target text

- data/indicator_15-1-1.csv
- meta/15-1-1.yml
- meta/fr/15-1-1.yml
- #536 
- Update land area denominator used in calculation of 15.1.1 data according to SME directions (also update sources and metadata)
> 15.1.1 calculation update

- .github/workflows/refresh-indicator-data.yml
- R/indicator_1-a-1.R
- R/indicator_11-2-1.R
- R/indicator_11-4-1.R
- R/indicator_17-3-1.R
- R/indicator_3-9-3.R
- R/indicator_3-c-1.R
- R/indicator_8-2-1.R
- R/indicator_8-9-1.R
- R/indicator_9-2-1.R
- automation_script.R
- translations/en/data.yml
- translations/fr/data.yml
Bugfixes/error handling in automation scripts and updates to workflows
> Automation updates

- indicator-config/17-3-1.yml
- meta/17-3-1.yml
- meta/fr/17-3-1.yml
- translations/en/global_indicators.yml
- translations/fr/global_indicators.yml
- #784 
- Set 17.3.1 to Exploring data sources
- Update with new name and metadata for 17.3.1
> indicator replacement 17.3.1

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- #787 
- Add latest updates to staging and production deployment workflows
> Workflows updates

- indicator-config/1-2-1.yml
- indicator-config/1-4-1.yml
- indicator-config/3-1-2.yml
- meta/1-1-1.yml
- meta/1-4-2.yml
- meta/3-1-1.yml
- meta/3-1-2.yml
- meta/3-3-5.yml
- meta/4-1-2.yml
- meta/fr/1-1-1.yml
- meta/fr/1-3-1.yml
- meta/fr/1-4-2.yml
- meta/fr/3-1-1.yml
- meta/fr/3-1-2.yml
- meta/fr/3-3-5.yml
- meta/fr/4-1-2.yml
- #796 
- 1.1.1 and 1.4.2 metadata update
- 1.2.1 target line
- 1.3.1 typo correction
- 1.4.1 data_start_values bugfix
- #802 
- 3.3.5 typo correction
- metadata formatting
- #804 
- 4.1.2 typo corrections
- metadata formatting
> Final review goals 1 4

- data/indicator_6-3-2.csv
- #817 
- Fix 6.3.2 data so that Total = Excellent + Good
- Updated with latest data from source
- Other bugfixes for 6.3.2 data
> 6.3.2 data correction
